name: test_flutter_charts4
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http:
  flutter_riverpod:
  freezed_annotation:
  json_annotation:

  fl_chart: ^0.55.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:
  freezed:
  json_serializable:

flutter:

  uses-material-design: true
